name: Deploy Django to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies and Deploy
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Uncomment if you want to run migrations
        # python manage.py migrate
        # Now, deploy
        echo "Deploying to Azure App Service..."
        # Use the Azure CLI or any method to deploy if needed
        # This might be adjusted depending on your deployment method
        # You can also use azure/webapps-deploy if it fits your workflow

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: azapp-test-dev-001   # Your Azure App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
