name: Deploy Django to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate  # Activate the virtual environment (this will be effective only in the current run)
    
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip
        pip install -r requirements.txt
   
    # - name: Run database migrations
    #   run: |
    #     source venv/bin/activate
    #     python manage.py migrate

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: azapp-test-dev-001   # Your Azure App Service name
        # slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
